- src/lib/components/dashboard/sidebar/Sidebar.svelte
Closes #36 
https://user-images.githubusercontent.com/43268759/236622003-995947e6-4fef-47b7-ab12-ca83bd14225d.mov
> feat: add select/deselect all repos

- src/lib/components/dashboard/Banner.svelte
- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/index.ts
- src/lib/components/landing/DownloadButton.svelte
- src/routes/+layout.svelte
- src/routes/+layout.ts
- src/routes/+page.svelte
- src/routes/login/+page.svelte
> feat(front): add download or open app banner

- .github/workflows/ci.yml
- package.json
- src-tauri/build.rs
- src-tauri/src/main.rs
> chore: lint & format Rust

- src/routes/+layout.ts
- src/routes/auth/callback/+server.ts
- src/routes/auth/login/+server.ts
- src/routes/login/+page.svelte
> feat(front): improve auth from app

- src/lib/components/dashboard/Notification.svelte
- src/lib/stores/stores.ts
- src/routes/dashboard/+page.svelte
> fix: wrong notification number in menubar

- package.json
- pnpm-lock.yaml
- src/lib/components/common/ScrollbarContainer.svelte
- src/lib/components/common/index.ts
- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/NotificationColumn.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/routes/+layout.ts
> feat(front): add custom scrollbar

- package.json
- src/routes/+layout.svelte
> fix: deep-link on windows

- src/lib/components/common/InlineSelect.svelte
- src/lib/components/common/ScrollbarContainer.svelte
- src/lib/components/common/Separator.svelte
- src/lib/components/common/index.ts
- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/NotificationColumn.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/stores/stores.ts
- src/lib/types/common-types.ts
- src/routes/dashboard/+page.svelte
> feat(front): notifications in vertical

- src/lib/helpers/createNotificationData.ts
- src/lib/types/github-types.ts
> fix(front): avoid error caused by unsupported notification type

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
> feat(back): store window state after closing the app

- src/lib/components/dashboard/sidebar/WatchedRepos.svelte
Allow filtering by a single repo or group quickly using shift/meta/ctrl/alt+click:
https://github.com/colinlienard/gitlight/assets/43268759/d36b660c-28c4-4f96-a851-d80875b22074
> feat(front): shift-click on repo/group to filter on it

- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/stores/stores.ts
- src/lib/types/common-types.ts
- src/routes/dashboard/+page.svelte
> feat(front): show/hide sidebar

- src/lib/components/dashboard/NotificationColumn.svelte
- src/lib/helpers/createNotificationData.ts
- src/lib/types/github-types.ts
> feat(front): support check suite notifications

- src/lib/components/common/Modal.svelte
- src/lib/components/common/ScrollbarContainer.svelte
- src/lib/components/settings/Accounts.svelte
- src/lib/components/settings/GithubSettings.svelte
- src/lib/components/settings/Preferences.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/components/settings/Update.svelte
- src/lib/stores/stores.ts
> feat(front): improve settings

- src/lib/components/dashboard/NotificationColumn.svelte
> perf(front): improve notification animations

- src/lib/helpers/createNotificationData.ts
- src/lib/helpers/index.ts
- src/lib/helpers/removeMarkdownSymbols.ts
> feat(front): remove markdown syntax in comments

- package.json
- pnpm-lock.yaml
- src/lib/components/common/Switch.svelte
- src/lib/components/common/Tooltip.svelte
- src/lib/components/dashboard/Notification.svelte
- src/lib/components/settings/LogOutButton.svelte
> core: migrate to svelte 4

- package.json
- src/lib/helpers/createNotificationData.ts
Also, fix the `packageManager` field inside `package.json`.
> fix(front): bot detection for merged and closed events

- .eslintrc.cjs
- src/lib/components/common/Modal.svelte
- src/lib/components/dashboard/Banner.svelte
- src/lib/components/dashboard/Notification.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/dashboard/sidebar/SidebarSection.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/helpers/createNotificationData.ts
- src/lib/helpers/removeMarkdownSymbols.ts
- src/routes/dashboard/+page.svelte
- Wrong number in system tray
- Better markdown replacement in comments
- Notification was re-showing a new when it just arrived and was set to pinned
- Log errors to the console
- Avoid getting multiple time same push notification
- Better "select/deselect all" behaviour
- Fix styling issues
> fix(front): small bugs

- src/lib/helpers/createNotificationData.ts
- src/lib/types/github-types.ts
> feat(front): add pr review event

- package.json
- pnpm-lock.yaml
- src/lib/components/common/Button.svelte
- src/lib/components/common/Input.svelte
- src/lib/components/common/Modal.svelte
- src/lib/components/common/ScrollbarContainer.svelte
- src/lib/components/common/ShrinkableWrapper.svelte
- src/lib/components/dashboard/Error.svelte
- src/lib/components/dashboard/Notification.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/settings/GithubSettings.svelte
- src/lib/components/settings/Permissions.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/components/settings/permissions/PatItem.svelte
- src/lib/components/settings/permissions/Permissions.svelte
- src/lib/components/settings/permissions/index.ts
- src/lib/helpers/createNotificationData.ts
- src/lib/helpers/fetchGithub.ts
- src/lib/icons/TrashIcon.svelte
- src/lib/icons/index.ts
- src/lib/stores/stores.ts
- src/lib/types/common-types.ts
- src/lib/types/github-types.ts
- src/routes/auth/login/+server.ts
- src/routes/dashboard/+page.svelte
- src/styles/_mixins.scss
> feat(front): add support for personal access tokens

- src/lib/components/common/InlineSelect.svelte
- src/lib/components/dashboard/sidebar/TypeFilters.svelte
- src/lib/components/settings/GithubSettings.svelte
- src/lib/components/settings/Preferences.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/components/settings/permissions/PatItem.svelte
- src/lib/components/settings/permissions/Permissions.svelte
- src/lib/stores/stores.ts
- src/lib/types/common-types.ts
- src/routes/dashboard/+page.svelte
> feat(front): add an option to fetch more notifications

- src/lib/components/common/Button.svelte
- src/lib/components/common/Modal.svelte
- src/lib/components/common/Tooltip.svelte
- src/lib/components/dashboard/DoneModal.svelte
- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/Notification.svelte
- src/lib/components/dashboard/NotificationColumn.svelte
- src/lib/components/landing/FakeNotifications.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/helpers/createNotificationData.ts
- src/lib/icons/DoubleCheckIcon.svelte
- src/lib/icons/RestoreIcon.svelte
- src/lib/icons/index.ts
- src/lib/types/common-types.ts
- src/routes/dashboard/+page.svelte
> feat(front): add done state for notifications

- src/lib/components/common/IconButton.svelte
- src/lib/components/dashboard/Notification.svelte
- src/lib/components/dashboard/NotificationColumn.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/dashboard/sidebar/TypeFilters.svelte
- src/lib/components/settings/GithubSettings.svelte
- src/lib/components/settings/Preferences.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/components/settings/Update.svelte
- src/lib/helpers/drag-actions.ts
- src/lib/helpers/dragActions.ts
- src/lib/helpers/index.ts
- src/lib/stores/stores.ts
- src/routes/dashboard/+page.svelte
> feat(front): add drag and drop

- src/lib/components/dashboard/Error.svelte
> fix(front): error snackbar overflow

- src/lib/components/common/Tooltip.svelte
- src/lib/components/dashboard/Notification.svelte
- src/lib/components/landing/FakeNotifications.svelte
- src/lib/components/settings/Preferences.svelte
- src/lib/helpers/createNotificationData.ts
- src/lib/stores/stores.ts
- src/lib/types/common-types.ts
- src/lib/types/index.ts
- src/lib/types/type-helpers.ts
- src/routes/dashboard/+page.svelte
> feat(front): add push notification reasons in settings

- src/lib/components/common/IconButton.svelte
- src/lib/components/common/Input.svelte
- src/lib/components/common/Switch.svelte
- src/lib/components/common/Tooltip.svelte
- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/notifications/DoneModal.svelte
- src/lib/components/dashboard/notifications/Notification.svelte
- src/lib/components/dashboard/notifications/NotificationColumn.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/dashboard/sidebar/SidebarSection.svelte
- src/lib/components/settings/Accounts.svelte
- src/styles/_mixins.scss
> refactor(front): improve ui/ux

- src/lib/components/common/InlineSelect.svelte
- src/lib/components/dashboard/Error.svelte
- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/notifications/NotificationColumn.svelte
- src/lib/components/dashboard/priorities/Priorities.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/landing/DownloadButton.svelte
- src/lib/components/settings/App.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/helpers/createNotificationData.ts
- src/lib/helpers/drag-actions.ts
- src/lib/helpers/removeMarkdownSymbols.ts
- src/routes/dashboard/+page.svelte
> fix(front): some issues

- src/lib/components/dashboard/sidebar/WatchedPersons.svelte
- src/lib/components/dashboard/sidebar/WatchedRepos.svelte
- src/routes/dashboard/+page.svelte
> fix(front): repos and persons not updating

- src/lib/components/common/Modal.svelte
- src/lib/components/common/index.ts
- src/lib/components/dashboard/sidebar/SidebarSearch.svelte
> fix(front): could not type `/` in inputs

- .github/workflows/release.yml
- src-tauri/tauri.conf.json
- src/lib/components/landing/DownloadButton.svelte
- src/lib/components/settings/App.svelte
- src/lib/components/settings/Settings.svelte
- src/routes/version/[target]/[version]/+server.ts
> **Warning**
> Do not merge before:
- testing the release action
- testing the updater endpoint with the target param
- removing the comment in `.github/workflows/release.yml` line 18
Closes #143
> core: build for apple silicon

- src/lib/components/settings/permissions/Permissions.svelte
- src/lib/helpers/createNotificationData.ts
> rework(front): add previously in discussions

- src/lib/components/dashboard/notifications/Notification.svelte
- src/lib/components/dashboard/notifications/NotificationLabels.svelte
- src/lib/features/delayed-hover.ts
- src/lib/features/drag-actions.ts
- src/lib/features/index.ts
> feat(front): clip labels

- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/notifications/Notification.svelte
- src/lib/components/dashboard/notifications/NotificationLabels.svelte
- src/lib/components/dashboard/notifications/NotificationList.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/dashboard/sidebar/WatchedPersons.svelte
- src/lib/components/settings/permissions/PatItem.svelte
- src/lib/features/createGithubNotificationData.ts
- src/lib/icons/ThreeDotsIcon.svelte
- src/lib/icons/index.ts
- src/lib/stores/stores.ts
- src/lib/types/common-types.ts
- src/routes/(app)/dashboard/+page.svelte
- src/routes/(tray)/tray/+page.svelte
> fix: multiple improvements

- .github/workflows/release.yml
- src-tauri/src/main.rs
- src/lib/components/dashboard/Main.svelte
- src/routes/(app)/dashboard/+page.svelte
- src/routes/(tray)/tray/+page.svelte
> refactor: improve tray-app

- src/lib/components/dashboard/notifications/DoneModal.svelte
- src/lib/components/dashboard/notifications/Notification.svelte
- src/lib/components/dashboard/notifications/NotificationColumn.svelte
- src/lib/components/dashboard/notifications/NotificationList.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/dashboard/sidebar/SidebarSection.svelte
- src/lib/components/dashboard/sidebar/WatchedRepos.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/features/createGithubNotificationData.ts
- src/lib/features/storage.ts
- src/lib/stores/stores.ts
- src/routes/(app)/dashboard/+page.svelte
- src/routes/(tray)/tray/+page.svelte
> feat: fix a few issues

- src/lib/components/dashboard/sidebar/Sidebar.svelte
> fix: prevent saving the page when Cmd+S

- src-tauri/Cargo.toml
- src-tauri/src/commands.rs
- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
- src/lib/components/common/InlineSelect.svelte
- src/lib/components/common/Switch.svelte
- src/lib/components/settings/Preferences.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/stores/stores.ts
- src/lib/types/common-types.ts
- src/routes/(app)/dashboard/+page.svelte
> feat: disable tray

- src-tauri/tauri.conf.json
- src/lib/components/dashboard/notifications/Notification.svelte
- src/lib/components/dashboard/notifications/NotificationDescription.svelte
- src/lib/features/createGithubNotificationData.ts
- src/routes/(app)/dashboard/+page.svelte
> fix: multiple small fixes

- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
- src/lib/components/dashboard/Main.svelte
- src/lib/components/dashboard/notifications/DoneModal.svelte
- src/lib/components/dashboard/notifications/Notification.svelte
- src/lib/components/dashboard/notifications/NotificationColumn.svelte
- src/lib/components/dashboard/notifications/NotificationDescription.svelte
- src/lib/components/dashboard/notifications/NotificationList.svelte
- src/lib/components/dashboard/notifications/NotificationStatus.svelte
- src/lib/components/dashboard/priorities/Priorities.svelte
- src/lib/components/dashboard/sidebar/TypeFilters.svelte
- src/lib/components/dashboard/sidebar/WatchedPersons.svelte
- src/lib/components/dashboard/sidebar/WatchedRepos.svelte
- src/lib/components/landing/FakeNotifications.svelte
- src/lib/components/login/GitlabLoginButton.svelte
- src/lib/components/settings/Preferences.svelte
- src/lib/features/createGithubNotificationData.ts
- src/lib/features/createGitlabNotificationData.ts
- src/lib/features/index.ts
- src/lib/features/intersection-action.ts
- src/lib/stores/stores.ts
- src/lib/types/common-types.ts
- src/lib/types/github-types.ts
- src/routes/(app)/dashboard/+page.svelte
- src/routes/(tray)/tray/+page.svelte
> refactor: improve some stuff

- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
- src/lib/components/dashboard/notifications/Notification.svelte
- src/lib/components/dashboard/notifications/NotificationColumn.svelte
- src/lib/components/dashboard/notifications/NotificationDescription.svelte
- src/lib/components/dashboard/sidebar/Sidebar.svelte
- src/lib/components/dashboard/sidebar/SidebarSearch.svelte
- src/lib/components/settings/Settings.svelte
- src/lib/features/createGithubNotificationData.ts
> fix: some gitlab issues

- src/lib/features/createGitlabNotificationData.ts
- src/lib/helpers/removeMarkdownSymbols.ts
> feat: parse markdown from gitlab

- src/lib/components/dashboard/notifications/Notification.svelte
- src/lib/components/dashboard/sidebar/WatchedRepos.svelte
- src/lib/components/landing/FakeNotifications.svelte
- src/lib/components/settings/gitlab-settings/RepoInput.svelte
- src/lib/features/createGithubNotificationData.ts
- src/lib/types/common-types.ts
- src/routes/(app)/dashboard/+page.svelte
> fix: gitlab subgroups url

- src/lib/components/common/Select.svelte
- src/lib/components/dashboard/sidebar/WatchedPersons.svelte
- src/lib/components/settings/github-settings/GithubSettings.svelte
- src/lib/features/createGithubNotificationData.ts
- src/lib/features/getGithubDiscussionData.ts
- src/lib/icons/PersonIcon.svelte
- src/lib/icons/index.ts
- src/lib/types/common-types.ts
- src/routes/(app)/deeplink/+page.svelte
> fix: some bugs and issues

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
https://devtools.crabnebula.dev/
> chore(tauri): add devtools

- src-tauri/src/main.rs
> fix(tray): unminimize on tray menu click on windows

- README.md
Thanks @Hacksore for adding GitLight in Homebrew!
> docs: add homebrew install command

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> chore: bump cargo time dependency

- src/lib/components/login/GitlabLoginButton.svelte
> fix(front): more permissive url for gitlab self-hosted url
